// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2YobVX9GUqSKPY1wmCgkCTc7Ms4IEmyk',
    appId: '1:1043970138842:web:2f68b811784cc1f3633be3',
    messagingSenderId: '1043970138842',
    projectId: 'prosus-997bb',
    authDomain: 'prosus-997bb.firebaseapp.com',
    databaseURL: 'https://prosus-997bb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prosus-997bb.appspot.com',
    measurementId: 'G-YJ69KMVVXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC699W4jN0l3pGRVSvy6phIlxt-bHDVgTg',
    appId: '1:1043970138842:android:ee32d9263b4f3a5e633be3',
    messagingSenderId: '1043970138842',
    projectId: 'prosus-997bb',
    databaseURL: 'https://prosus-997bb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prosus-997bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQQLXuClDPyBHk6Hf-UoanE9DnHXltnm4',
    appId: '1:1043970138842:ios:79dfbd2ef7ab44b9633be3',
    messagingSenderId: '1043970138842',
    projectId: 'prosus-997bb',
    databaseURL: 'https://prosus-997bb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prosus-997bb.appspot.com',
    iosClientId: '1043970138842-iq95rh3fe9fcia1mbgrg3d76cf6qb09j.apps.googleusercontent.com',
    iosBundleId: 'nl.prosuss.dev.prosusFinalApp',
  );
}
